/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seorientacionvocacional;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Prado
 */
public class TestAreas extends javax.swing.JFrame {
    String r;
    

    /**
     * Creates new form TestAreas
     */
    
    BaseReglas objbr = new BaseReglas();
    
    public TestAreas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("TEST");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        btnResultado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox1.setText("1. Lees artículos frecuentemente ");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 30));

        jCheckBox2.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox2.setText("2. Facilidad para hablar en público");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 30));

        jCheckBox3.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox3.setText("3. Te gusta innovar");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 30));

        jCheckBox4.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox4.setText("4. Pensamiento positivo ante problemas");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 30));

        jCheckBox5.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox5.setText("5. Exigente con tu equipo de trabajo");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 30));

        jCheckBox6.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox6.setText("6. Te gusta armar rompecabezas y puzzles");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, 30));

        jCheckBox7.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox7.setText("7. Te gusta ser líder de equipo");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 30));

        jCheckBox8.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox8.setText("8. Interés por los temas del pasado");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, 30));

        jCheckBox9.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox9.setText("9. Prefieres el trabajo manual sobe el intelectual");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, 30));

        jCheckBox10.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox10.setText("10. Te es importante compartir tus ideas");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, 30));

        jCheckBox11.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox11.setText("11. Disfrutas trabajar con números y registrarlos de manera ordenada");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, 30));

        jCheckBox12.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox12.setText("12. Tienes habilidad en las matemáticas y estadística");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, 30));

        jCheckBox13.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox13.setText("13. Investigas y hablas sobre finanzas ");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, 30));

        jCheckBox14.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox14.setText("14. Te interesa saber el funcionamiento de las cosas");
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, 30));

        jCheckBox15.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox15.setText("15. Te gusta resolver y dar solucion a problemas");
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, 30));

        jCheckBox16.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox16.setText("16. Te interesa entender el comportamiento humano");
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, 30));

        jCheckBox17.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox17.setText("17. Facilidad para recordar fechas y acontecimientos importantes");
        jCheckBox17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox17ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, -1, 30));

        jCheckBox18.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox18.setText("18. Puedes realizar conclusiones basándote en tu propio criterio");
        jCheckBox18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox18ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, -1, 30));

        jCheckBox19.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox19.setText("19. Te consideras una persona creativa");
        jCheckBox19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox19ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, -1, 30));

        jCheckBox20.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox20.setText("20. Eres apto para las matemáticas, física y ciencias relacionadas");
        jCheckBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox20ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 690, -1, 30));

        jCheckBox21.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox21.setText("21. Lees artículos científicos frecuentemente");
        jCheckBox21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox21ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 720, -1, 30));

        jCheckBox22.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox22.setText("22. Te inquieta conocer el cuerpo humano");
        jCheckBox22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox22ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 750, -1, 30));

        jCheckBox23.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox23.setText("23. Te gustaría aplicar tus conocimientos en la solución de problemas");
        jCheckBox23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox23ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 780, -1, 30));

        jCheckBox24.setBackground(new java.awt.Color(247, 247, 247));
        jCheckBox24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox24.setText("24. Eres ingenioso, curioso y te gustan las matemáticas, física y química");
        jCheckBox24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox24ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 810, -1, 30));

        btnResultado.setText("Resultado");
        btnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 860, -1, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 80, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Selecciona los enunciados que te describan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TEST DE ORIENTACIÓN VOCACIONAL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(43, 43, 43))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, -1));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 550));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INICIAR SESIÓN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(67, 67, 67))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 20, 330, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void jCheckBox17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox17ActionPerformed

    private void jCheckBox18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox18ActionPerformed

    private void jCheckBox19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox19ActionPerformed

    private void jCheckBox20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox20ActionPerformed

    private void jCheckBox21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox21ActionPerformed

    private void jCheckBox22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox22ActionPerformed

    private void jCheckBox23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox23ActionPerformed

    private void jCheckBox24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox24ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void btnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoActionPerformed
        String v1="", v2="", v3="", v4="", v5="", v6="", v7="", v8="", v9="", 
                v10="", v11="", v12="", v13="", v14="", v15="", v16="", v17="", 
                v18="", v19="", v20="", v21="", v22="", v23="", v24="";
        
        float soc=0, sal=0, exa=0, art=0, eco=0, ing=0;
        float dsoc=0, dsal=0, dexa=0, dart=0, deco=0, ding=0, dsuma=0;
        float select=0;
        
        if(jCheckBox1.isSelected())
        {
            v1="si";
            soc=soc+5;
            select=select+5;
            
        }
        else
        {
            v1="no";
        }    
        
        if(jCheckBox2.isSelected())
        {
            v2="si";
            //soc++;
            //select++;
            soc=soc+3;
            select=select+3;
        }
        else
        {
            v2="no";
        }
        
        if(jCheckBox3.isSelected())
        {
            v3="si";
            ing=ing+10;
            select=select+10;
        }
        else
        {
            v3="no";
        }
         if(jCheckBox4.isSelected())
        {
            v4="si";
            sal=sal+3;
            select=select+3;
        }
        else
        {
            v4="no";
        }
         if(jCheckBox5.isSelected())
        {
            v5="si";
            eco++;
            select++;
        }
        else
        {
            v5="no";
        }
        if(jCheckBox6.isSelected())
        {
            v6="si";
            //art++;
            //select++;
            art=art+7;
            select=select+7;
        }
        else
        {
            v6="no";
        }
        if(jCheckBox7.isSelected())
        {
            v7="si";
            eco=eco+5;
            select=select+5;
        }
        else
        {
            v7="no";
        }
        if(jCheckBox8.isSelected())
        {
            v8="si";
            soc=soc+10;
            select=select+10;
        }
        else
        {
            v8="no";
        }
        if(jCheckBox9.isSelected())
        {
            v9="si";
            art=art+8;
            select=art+8;
        }
        else
        {
            v9="no";
        }
        if(jCheckBox10.isSelected())
        {
            v10="si";
            sal++;            
            select++;
        }
        else
        {
            v10="no";
        }
        if(jCheckBox11.isSelected())
        {
            v11="si";
            eco=eco+10;
            //eco++;
            //select++;
            select=select+10;
        }
        else
        {
            v11="no";
        }
        if(jCheckBox12.isSelected())
        {
            v12="si";
            //eco++;
            //select++;
            eco=eco+5;
            select=select+5;
            
            
        }
        else
        {
            v12="no";
        }
        if(jCheckBox13.isSelected())
        {
             v13="si";
             //eco++;
             //select++;
             eco=eco+5;
             select=select+5;
        }
        else
        {
            v13="no";
        }
        if(jCheckBox14.isSelected())
        {
             v14="si";
             //ing++;
             //select++;
             ing=ing+9;
             select=select+9;
        }
        else
        {
            v14="no";
        }
        if(jCheckBox15.isSelected())
        {
            v15="si";
            ing=ing+5;
            select=select+5;
        }
        else
        {
            v15="no";
        }
        if(jCheckBox16.isSelected())
        {
             v16="si";
             //soc++;
             //select++;
             soc=soc+5;
             select=select+5;
        }
        else
        {
            v16="no";
        }
        if(jCheckBox17.isSelected())
        {
             v17="si";
             //soc++;
             //select++;
             soc=soc+3;
             select=select+3;
        }
        else
        {
            v17="no";
        }
        if(jCheckBox18.isSelected())
        {
             v18="si";
             soc++;
             select++;
        }
        else
        {
            v18="no";
        }
        if(jCheckBox19.isSelected())
        {
            v19="si";
            //art++;
            //select++;
            art=art+7;
            select=select+7;
        }
        else
        {
            v19="no";
        }        
        if(jCheckBox20.isSelected())
        {
             v20="si";
            
            //exa++;
            //select++;
            exa=exa+10;
            select=select+10;
            
        }
        else
        {
            v20="no";
        }
        if(jCheckBox21.isSelected())
        {
             v21="si";
            //sal++;
            //select++;
            sal=sal+5;
            select=select+5;
        }
        else
        {
            v21="no";
        }
        if(jCheckBox22.isSelected())
        {
            v22="si";
            //sal++;
            //select++;
            sal=sal+10;
            select=select+10;
        }
        else
        {
            v22="no";
        }
        if(jCheckBox23.isSelected())
        {
            v23="si";
            sal=sal+3;
            //sal++;
            select=select+3;
            //select++;
        }
        else
        {
            v23="no";
        }
        if(jCheckBox24.isSelected())
        {
             v24="si";
             //exa++;
             //select++;
             exa=exa+5;
             select=select+5;
        }
        else
        {
            v24="no";
        }  
        
        /*System.out.println("\nV1="+v1+"\nV2="+v2+"\nV3="+v3+"\nV4="+v4+"\nV5="+v5+
                "\nV6="+v6+"\nV7="+v7+"\nV8="+v8+"\nV9="+v9+"\nV10="+v10+
                "\nV11="+v11+"\nV12="+v12+"\nV13="+v13+"\nV14="+v14+"\nV15="+v15+
                "\nV16="+v16+"\nV17="+v17+"\nV18="+v18+"\nV19="+v19+"\nV20="+v20+
                "\nV21="+v21+"\nV22="+v22+"\nV23="+v23+"\nV24="+v24);*/
        
        r=objbr.getCarrera(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, 
                v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24);
        System.out.println("Area="+r);
        jLabel2.setText(r);
        
        dsoc = (soc/select);
        dsal = (sal/select);
        dexa = (exa/select);
        dart = (art/select);
        deco = (eco/select);
        ding = (ing/select);
        dsuma = (dsoc + dsal + dexa + dart + deco + ding);
        
        dsoc = (dsoc*100);
        dsal = (dsal*100);
        dexa = (dexa*100);
        dart = (dart*100);
        deco = (deco*100);
        ding = (ding*100);
                
        System.out.println("soc=" +dsoc);
        System.out.println("sal=" +dsal);
        System.out.println("exa=" +dexa);
        System.out.println("art=" +dart);
        System.out.println("eco=" +deco);
        System.out.println("soc=" +dsoc);
        System.out.println("suma=" +dsuma);
        
        JOptionPane.showMessageDialog(null,"El Area al que tu perfil está enfocado es"
                + "\nCiencias Sociales y Humanidades: "+dsoc+"%"
                + "\nCiencias de la Salud: "+dsal+"%"
                + "\nCiencias Exactas: "+dexa+"%"
                + "\nArtisticas, Arquitectura y Diseño: "+dart+"%"
                + "\nEconómico-Administrativas: "+deco+"%"
                + "\nIngenierias: "+dsoc+"%");
               
        if(r=="Ciencias Sociales y Humanidades"){
            /*JOptionPane.showMessageDialog(null,"El Area al que tu perfil está enfocado es "+r+"."
            +"\nLas carreras más adecuadas de acuerdo a tu perfil son:"
            +"\n* Licenciatura en Antropología"
            +"\n* Licenciatura en Ciencias Políticas"
            +"\n* Licenciatura en Comunicación"
            +"\n* Licenciatura en Derecho"
            +"\n* Licenciatura en Sociología"
            +"\n* Licenciatura en Historia"
            +"\n* Licenciatura en Relaciones Internacionales");*/
            this.setVisible(false);
            ResultadoCienciasSociales Acc = new ResultadoCienciasSociales();
            Acc.setVisible(true);    
            
        }
        else if(r=="Ciencias de la Salud"){
            /*JOptionPane.showMessageDialog(null,"El Area al que tu perfil está enfocado es "+r+"."
            +"\nLas carreras más adecuadas de acuerdo a tu perfil son:"
            +"\n* Licenciatura en Medicina"
            +"\n* Licenciatura en Enfermería"
            +"\n* Licenciatura en Cirujano Dentista"
            +"\n* Licenciatura en Fisioterapia"
            +"\n* Licenciatura en Odontología"
            +"\n* Licenciatura en Neurociencias");*/
            this.setVisible(false);
            ResultadoCienciasSalud Acc = new ResultadoCienciasSalud();
            Acc.setVisible(true); 
        }
        else if(r=="Ciencias Exactas"){
            /*JOptionPane.showMessageDialog(null,"El Area al que tu perfil está enfocado es "+r+"."
            +"\nLas carreras más adecuadas de acuerdo a tu perfil son:"
            +"\n* Licenciatura en Física"
            +"\n* Licenciatura en Química"
            +"\n* Licenciatura en Geología"
            +"\n* Licenciatura en Bioquímica"
            +"\n* Licenciatura en Biología"
            +"\n* Licenciatura en Ciencias Computacionales"
            +"\n* Licenciatura en Ciencia de los Materiales");*/
            this.setVisible(false);
            ResultadoCienciasExactas Acc = new ResultadoCienciasExactas();
            Acc.setVisible(true); 
        }
        else if(r=="Artisticas, Arquitectura y Diseño"){
            /*JOptionPane.showMessageDialog(null,"El Area al que tu perfil está enfocado es "+r+"."
            +"\nLas carreras más adecuadas de acuerdo a tu perfil son:"
            +"\n* Licenciatura en Música"
            +"\n* Licenciatura en Danza"
            +"\n* Licenciatura en Arte Dramático"
            +"\n* Licenciatura en Artes Visuales"
            +"\n* Licenciatura en Arquitectura"
            +"\n* Licenciatura en Diseño Gráfico"
            +"\n* Licenciatura en Diseño de Modas"
            +"\n* Licenciatura en Artes Plásticas");*/
            this.setVisible(false);
            ResultadoArtisticas Acc = new ResultadoArtisticas();
            Acc.setVisible(true); 
        }
        else if(r=="Economico - Administrativas"){
            /*JOptionPane.showMessageDialog(null,"El Area al que tu perfil está enfocado es "+r+"."
            +"\nLas carreras más adecuadas de acuerdo a tu perfil son:"
            +"\n* Licenciatura en Contaduría"
            +"\n* Licenciatura en Administración"
            +"\n* Licenciatura en Economía"
            +"\n* Licenciatura en Comercio Exterior"
            +"\n* Licenciatura en Mercadotecnia"
            +"\n* Licenciatura en Turismo"
            +"\n* Licenciatura en Negocios Internacionales"
            +"\n* Licenciatura en Gestión Empresarial"
            +"\n* Licenciatura en Gestión Turística");*/
            this.setVisible(false);
            ResultadoCienciasEconomico Acc = new ResultadoCienciasEconomico();
            Acc.setVisible(true); 
        }
        else if(r=="Ingenierias"){
            /*JOptionPane.showMessageDialog(null,"El Area al que tu perfil está enfocado es "+r+"."
            +"\nLas carreras más adecuadas de acuerdo a tu perfil son:"
            +"\n* Ingeniería Industrial"
            +"\n* Ingeniería Civil"
            +"\n* Ingeniería en Electrónica "
            +"\n* Ingeniería en Mecatrónica"
            +"\n* Ingeniería en Sistemas Computacionales"
            +"\n* Ingeniería en Robótica Industrial"
            +"\n* Ingeniería en Biotecnología"
            +"\n* Ingeniería en Nanotecnología"
            +"\n* Ingeniería en Energias Renovables");*/
            this.setVisible(false);
            ResultadoIngenieria Acc = new ResultadoIngenieria();
            Acc.setVisible(true); 
        }
        else if(soc > sal && soc > exa && soc > art && soc > eco && soc > ing){
            this.setVisible(false);
            ResultadoCienciasSociales Acc = new ResultadoCienciasSociales();
            Acc.setVisible(true);  
        }
        else if(sal > soc && sal > exa && sal > art && sal > eco && sal > ing){
            this.setVisible(false);
            ResultadoCienciasSalud Acc = new ResultadoCienciasSalud();
            Acc.setVisible(true); 
        }
        else if(exa > sal && exa > soc && exa > art && exa > eco && exa > ing){
            this.setVisible(false);
            ResultadoCienciasExactas Acc = new ResultadoCienciasExactas();
            Acc.setVisible(true);
        }
        else if(art > sal && art > exa && art > soc && art > eco && art > ing){
            this.setVisible(false);
            ResultadoArtisticas Acc = new ResultadoArtisticas();
            Acc.setVisible(true);
        }
        else if(eco > sal && eco > exa && eco > art && eco > soc && eco > ing){
            this.setVisible(false);
            ResultadoCienciasEconomico Acc = new ResultadoCienciasEconomico();
            Acc.setVisible(true);  
        }
        else if(ing > sal && ing > exa && ing > art && ing > eco && ing > soc){
            this.setVisible(false);
            ResultadoIngenieria Acc = new ResultadoIngenieria();
            Acc.setVisible(true); 
        }
        else{
            JOptionPane.showMessageDialog(null,"No es posible determinar");
            /*this.setVisible(false);
            ResultadoCienciasExactas Acc = new ResultadoCienciasExactas();
            Acc.setVisible(true);*/
        }
        
        /*this.setVisible(false);
        AccesoUsuario Acc = new AccesoUsuario();
        Acc.setVisible(true); */       
    }//GEN-LAST:event_btnResultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestAreas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestAreas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestAreas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestAreas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestAreas().setVisible(true);
            }
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResultado;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
